### ISSUE TITLE
Future of this plugin

### ISSUE THREAD

**Issue by bradenmacdonald** [open-craft/tutor-contrib-arm64#1]
@regisb any thoughts on the future of this plugin? I've been using it this whole time and it works really well. Not sure if anyone / who else is using it.

For changing the DB image, since MySQL 8 seems quite stable and working well, we could incorporate that as the default into tutor main, at least for ARM64.

As for docker images:

For now, I continue to update the ARM64 docker images that I host here once in a while.

For images, we could either:
* Add a GitHub CI workflow script to update these images on a regular basis and keep them unofficial. Add this to the tutor-contrib index.
* Update your official images to be dual-architecture and add support for ARM64. Deprecate this plugin.
* Not publish any images and recommend that users build their own. Deprecate this plugin.

It seems like the documentation at https://docs.tutor.overhang.io/tutorials/arm64.html also needs to be updated as it still mentions MariaDB.

**Comment by regisb** [comment]
I do recognize the usefulness of this plugin. I wish I could backport the changes in Tutor core or make the plugin official, but:

- Setting up a multi-arch CI infrastructure is hard.
- I am not an arm64 user so it's difficult for me to test the plugin.

Thus, I propose that we go with option 1:

> Add a GitHub CI workflow script to update these images on a regular basis and keep them unofficial. Add this to the tutor-contrib index.

That way, Tutor users could start using plugin with just:

    tutor plugins install arm64
    tutor plugins enable arm64

Would you be OK with maintaining the plugin?

**Comment by bradenmacdonald** [comment]
Yes, I would be OK with that. I've been maintaining it already, without any issues so far.
I'll look into updating the images automatically and I'll plan to open a PR to update the docs.

**Comment by feoh** [comment]
Hiya! I tried using this plugin yesterday at OpenEdX 2023 as the EdX Hooks talk assumed a working Tutor setup.

I wasn't able to get it to work. I performed the following steps:

```
mkdir tutor-arm64-workspace
cd tutor-arm64-workspace

python3.10 -m venv tutor-arm64-install-venv
. ./tutor-arm64-install-venv/bin/activate
pip install git+https://github.com/open-craft/tutor-contrib-arm64
tutor plugins enable arm64
```
The plugins enable command printed an error about invalid plugin name or similar. I apologies I didn't capture it from my buffer.

And then tutor local quickstart OR tutor launch both failed with the same error about being unable to find a mysql container for ARM64.

Should I have changed the db to mariaDB as per the mainline [ARM64 install doc](https://docs.tutor.overhang.io/tutorials/arm64.html)?

I would love to collaborate with you in testing this plugin, improving the documentation, and adding it to the mainline ARM64 install doc so folks can have an easier time getting started on M1/M2 macs.

Thanks in advance!

**Comment by bradenmacdonald** [comment]
^ Re the above issue, see #2.

**Comment by bradenmacdonald** [comment]
@regisb I have a PR open that sets up fully automated daily builds of this ARM64 image for Tutor master + nightly. Thanks to your work in https://github.com/overhangio/tutor/pull/812 which turned out to be necessary. If you are interested or have any feedback on the approach, please check it out at https://github.com/open-craft/tutor-contrib-arm64/pull/3/files

In particular I'm wondering if triggering a daily build for the master version may result in excess image downloads; maybe I should put in a check to only push the image if a version doesn't yet exist, but I'm not quite sure how to check that easily.

**Comment by bradenmacdonald** [comment]
Closing this issue now because:
* Properly versioned automated daily builds are working: https://github.com/open-craft/tutor-contrib-arm64/pkgs/container/openedx-arm64 (still may need to reduce the frequency; we'll see).
* I will be maintaining this plugin indefinitely
* The [official docs](https://docs.tutor.overhang.io/tutorials/arm64.html) now mention this plugin

I do still need to add this to the tutor-contrib index.
